.F.
======================================================================
FAIL: test_above_freezing_at (__main__.TestAboveFreezing)
Test a temperature that is at freezing.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test_above_freezing.py", line 33, in test_above_freezing_at
    "The temperature is at the freezing mark.")
AssertionError: False != True : The temperature is at the freezing mark.

----------------------------------------------------------------------
Ran 3 tests in 0.001s

FAILED (failures=1)